### PR TITLE
Add PlantSimEngine compatibilities

### PR DESCRIPTION
**Pull request by bspanoghe**
As requested in #55

### CODE REVIEW

**Comment by VEZY** [comment]
Hey @bspanoghe, thanks for the PR! Unfortunately, the tests are broken. This comes from:

- changes in the way we make multiscale simulations in PlantSimEngine
- changes in MultiScaleTreeGraph that handle the node attributes and MTG (symbols, scales...) differently
- changes in PlantGeom that has a lot of improvements compared to the one used in the tests.

Are you in a rush for this PR? Because I have little time to work on it right now unfortunately. The plan is to first make a release of PlantGeom (I have to document the new things first), then we can update the versions of all packages in this one, update the doc, update the tests and voilà!

**Comment by VEZY** [comment]
Note that the compat entry to PlantSimEngine, MultiScaleTreeGraph and PlantGeom will be set to the latest ones because they have breaking changes.

**Comment by VEZY** [comment]
One step closer to a release of PlantBiophysics: I made a release of PlantGeom.

**Comment by VEZY** [comment]
Hey @bspanoghe, I finally found time to merge. I'll release it as soon as the tests on the main branch are complete.

**Comment by bspanoghe** [comment]
Thanks for keeping me updated!

**Pull request merged**
